### ISSUE TITLE
Masalah Fragment 

### ISSUE THREAD

**Issue by v-rie** [farizdotid/mahasiswa-app-android#1]
Kalau mau pake fragment gmn ya? 
selalu _E/RecyclerView: No adapter attached; skipping layout._ 
udah aku bolak balik pasang atur adapternya masih sama errror macam itu...

**Comment by farizdotid** [comment]
init adapternya itu dimana gan? Pastebin code di fragmentnya dong.

**Comment by v-rie** [comment]
https://pastebin.com/keSP2FE8
itu editan terakhirku.. minta bantuannya bro. 
suwun.

**Comment by farizdotid** [comment]
Coba gan dibawah code 
rvReferral.setAdapter(bonusReferralAdapter);

tambahin method notifydatasetchanged : 
bonusReferralAdapter.notifyDataSetChanged();

**Comment by v-rie** [comment]
https://pastebin.com/g03vts5v

minta tolong cek lagi bro..
udah aku revisi tapi masih sama.
cuma di fragment doang yg masalah macam ini. dan di GET, kalo POST lancar..

**Comment by farizdotid** [comment]
taro method getResultListReferral(); didalem onCreateView gan.

`@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
 
        View view = inflater.inflate(R.layout.fragment_referal, container, false);
        ButterKnife.bind(this, view);
        sharedPrefManager = new SharedPrefManager(this.getActivity());
 
        mApiService = UtilsApi.getAPIService();
 
        bonusReferralAdapter = new BonusReferralAdapter(mContext, semuadatareferralBonusList);
        RecyclerView.LayoutManager mLayoutManager = new LinearLayoutManager(mContext);
        rvReferral.setLayoutManager(mLayoutManager);
        rvReferral.setItemAnimator(new DefaultItemAnimator());
        getResultListReferral();
       return view;
    }`

**Comment by v-rie** [comment]
Masih sama, di Logcat data udah keluar panjang lebar., 
Tapi selalu E/RecyclerView: No adapter attached; skipping layout.

**Comment by farizdotid** [comment]
hmm aneh. Coba pastebin adapternya gan

**Comment by v-rie** [comment]
https://pastebin.com/qvd69Upc
Solve masalahanya, tapi gantian datanya gamau masuk.. 
haduh...

**Comment by farizdotid** [comment]
` private RecyclerView mRecyclerView;
    private Context mContext;
    private RecyclerView.Adapter mAdapter;
    private List<SemuadatareferralBonus> semuadatareferralBonusList = new ArrayList<>();
    private BaseApiService mApiService;
    private BonusReferralAdapter adapter;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_referal, container, false);

        mApiService = UtilsApi.getAPIService();
        mRecyclerView = (RecyclerView) view.findViewById(R.id.rvReferral);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
        //improve recycler view performance as long all view are the same height and width
        mRecyclerView.setHasFixedSize(true);
        mAdapter = new BonusReferralAdapter(mContext, semuadatareferralBonusList);
        mRecyclerView.setAdapter(mAdapter);

        return view;
    }


    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        getActivity().setTitle(R.string.referal);
        mApiService.getReferralBonus().enqueue(new Callback<ResponseReferralBonus>() {
            @Override
            public void onResponse(Call<ResponseReferralBonus> call, Response<ResponseReferralBonus> response) {
                if (response.isSuccessful()){
                    Toast.makeText(getContext(), "Error --> 1", Toast.LENGTH_LONG).show();

                }else{
                    Toast.makeText(getContext(), "Error --> 2", Toast.LENGTH_LONG).show();
                }

            }

            @Override
            public void onFailure(Call<ResponseReferralBonus> call, Throwable t) {
                Toast.makeText(getContext(), "Error --> 3", Toast.LENGTH_LONG).show();
            }
        });
    }`

**Comment by farizdotid** [comment]
bentar, malah kepencet close haha

**Comment by farizdotid** [comment]
kode yang sekarang gimana gan? kok ane liat berubah lagi?

**Comment by v-rie** [comment]
https://pastebin.com/W05qSwUB
Ini udah aku revisi bro..

**Comment by farizdotid** [comment]
coba kaya gini gan : 
` private RecyclerView mRecyclerView;
    private Context mContext;
    private List<SemuadatareferralBonus> semuadatareferralBonusList = new ArrayList<>();
    private BaseApiService mApiService;
    private BonusReferralAdapter adapter;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_referal, container, false);

        mApiService = UtilsApi.getAPIService();
        mRecyclerView = (RecyclerView) view.findViewById(R.id.rvReferral);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
        //improve recycler view performance as long all view are the same height and width
        mRecyclerView.setHasFixedSize(true);
        adapter = new BonusReferralAdapter(mContext, semuadatareferralBonusList);
        mRecyclerView.setAdapter(adapter);

        mApiService.getReferralBonus().enqueue(new Callback<ResponseReferralBonus>() {
            @Override
            public void onResponse(Call<ResponseReferralBonus> call, Response<ResponseReferralBonus> response) {
                if (response.isSuccessful()){
                    final List<SemuadatareferralBonus> semuadatareferralBonus = response.body().getSemuadatareferral();
                    mRecyclerView.setAdapter(new BonusReferralAdapter(mContext, semuadatareferralBonus));
                    adapter.notifyDataSetChanged();
                }else{
                    Toast.makeText(getContext(), "Error --> 2", Toast.LENGTH_LONG).show();
                }

            }

            @Override
            public void onFailure(Call<ResponseReferralBonus> call, Throwable t) {
                Toast.makeText(getContext(), "Error --> 3", Toast.LENGTH_LONG).show();
            }
        });

        return view;
    }


    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        getActivity().setTitle(R.string.referal);
        
    }`

**Comment by v-rie** [comment]
Sama saja bro.. Masih ngga muncul, heran saya.
dibolak balik masih sama kyk gitu..

Adapternya ini.
https://pastebin.com/H5KzGbTp

**Comment by farizdotid** [comment]
hmm aneh bener wkwk atau engga coba gini : 
else{
                Toast.makeText(getContext(), "Error --> 2", Toast.LENGTH_LONG).show();
            }

kode itu hapus aja.

**Comment by v-rie** [comment]
sama saja bro, hha
liat2 di stackoverflow banyak juga yg dapat kasus kyk saya.

**Comment by farizdotid** [comment]
Gini aja deh coba gan : 
`mApiService.getReferralBonus().enqueue(new Callback<ResponseReferralBonus>() {
        @Override
        public void onResponse(Call<ResponseReferralBonus> call, Response<ResponseReferralBonus> response) {
            if (response.isSuccessful()){
                final List<SemuadatareferralBonus> semuadatareferralBonus = response.body().getSemuadatareferral();
              
                disini kasih log dari semuadatareferralBonus.size()
            }

        }

        @Override
        public void onFailure(Call<ResponseReferralBonus> call, Throwable t) {
            Toast.makeText(getContext(), "Error --> 3", Toast.LENGTH_LONG).show();
        }
    });`

di log dulu data dari API ada atau engga. Btw, itu fragment ke init waktu kasus gimana gan?

**Comment by v-rie** [comment]
java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT 
Aku Log-in, nemu kesalahan di API nya...
mesti ada Object nyaa..

**Comment by farizdotid** [comment]
respon JSONnya emang kaya gimana gan?

**Comment by v-rie** [comment]
mestinya
JSON
```
 {
    "error": false,
    "message": "Berhasil mendapatkan data dosen",
    "semuadosen": [
        {
            "id": "1",
            "nama": "Fariz",
            "matkul": "Android Developer"
        }
    ]
}
```
nah punyaku
```
{
    "error": false,
    "message": "Berhasil mendapatkan data dosen",
    "semuadosen": 
        {
            "id": "1",
            "nama": "Fariz",
            "matkul": "Android Developer"
        }
    
}
```

cuma ga ada Object [] doang gabisa baca.

oh iya bro, kalo 
```
@DELETE("matkul/{idmatkul}")
    Call<ResponseBody> deteleMatkul(@Path("idmatkul") String idmatkul);
```

idmatkul berdasarkan SharedPrefManager bisa ngga?
jadi ketika aku buka activity barunih aku langsung manggil API berdasarkan usernameku atau IDku gitu.

**Comment by farizdotid** [comment]
Kalau response json seperti sekarang perlu diperhatiin class modelnya gan, soalnya di punya saya kan bentuknya array. 

idmatkul ini sebenernya parameter buat API gan, nah untuk value yang buat diisi di parameternya itu bebas mau data dari mana aja asalnya ( sharedpreferences, bundle, dll).

maksud @DELETE("matkul/{idmatkul}") : 
- Delete --> Http request
- matkul/{idmatkul} --> url dengan berparameter idmatkul ( idmatkul bisa didapet waktu ngeget semua matkul )

**Comment by v-rie** [comment]
Ohh, ngerti2....
suwun bro...
mantap bener dah...

**Comment by farizdotid** [comment]
sama2 gan :+1:
